starting worker pid=3749 on localhost:11354 at 12:30:26.294
starting worker pid=3746 on localhost:11354 at 12:30:26.296
starting worker pid=3747 on localhost:11354 at 12:30:26.298
starting worker pid=3745 on localhost:11354 at 12:30:26.299
starting worker pid=3751 on localhost:11354 at 12:30:26.300
starting worker pid=3750 on localhost:11354 at 12:30:26.316
starting worker pid=3748 on localhost:11354 at 12:30:26.322
Finished rep 5 / 14 at 2025-10-23 12:31:09.
Finished rep 6 / 14 at 2025-10-23 12:31:19.
Finished rep 7 / 14 at 2025-10-23 12:31:20.
Finished rep 8 / 14 at 2025-10-23 12:31:54.
Finished rep 9 / 14 at 2025-10-23 12:32:09.
Finished rep 10 / 14 at 2025-10-23 12:32:16.
Finished rep 11 / 14 at 2025-10-23 12:32:23.
Finished rep 3 / 14 at 2025-10-23 12:32:25.
Finished rep 2 / 14 at 2025-10-23 12:32:27.
Finished rep 1 / 14 at 2025-10-23 12:32:28.
Finished rep 4 / 14 at 2025-10-23 12:32:28.
Finished rep 12 / 14 at 2025-10-23 12:32:35.
Finished rep 14 / 14 at 2025-10-23 12:32:37.
Finished rep 13 / 14 at 2025-10-23 12:32:39.
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
In addition: Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
In addition: In addition: In addition: There were 50 or more warnings (use warnings() to see the first 50)In addition: There were 50 or more warnings (use warnings() to see the first 50)
There were 50 or more warnings (use warnings() to see the first 50)
There were 50 or more warnings (use warnings() to see the first 50)
Execution halted
Execution halted
Execution halted
There were 50 or more warnings (use warnings() to see the first 50)

Execution halted
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
In addition: In addition: There were 50 or more warnings (use warnings() to see the first 50)There were 50 or more warnings (use warnings() to see the first 50)

Execution halted
Execution halted
